spring:
  application:
    name: kafka-hands-on-service-producer

  kafka:
    producer:
      bootstrap-servers: localhost:9090
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#    consumer:
#      bootstrap-servers: localhost:9090
#      #group-id: sk-group-100
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.sk

sk:
 kafka:
  topic: sk-good-topic-200

server:
  port: 8888