spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skDB
    username: postgres
    password: password

  jpa:
    #database-platform: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        cache:
          use_second_level_cache: true
